CREATE DATABASE IF NOT EXISTS tcc;
use tcc;

CREATE TABLE if NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  lastname VARCHAR(100),
  email VARCHAR(150),
  password VARCHAR(200),
  image VARCHAR(200),
  token VARCHAR(200),
  bio TEXT
);

CREATE TABLE IF NOT EXISTS objects (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  description TEXT,
  image VARCHAR(200),
  users_id INT UNSIGNED,
  FOREIGN KEY (users_id) REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);